### ISSUE TITLE
Type Boolean not supported in metadata.rb

### ISSUE THREAD

**Issue by alainchiasson** [xhost-cookbooks/system#10]
While it usualy does not seem to matter - we user RightScale, which depends on the metadata.rb information. From the chef docs at https://docs.chef.io/cookbook_repo.html : 

> type (the type of value, either string, array, or hash)  

Rightscale is strict about this : 

In your metadata.rb file - you have a type boolean : 

```
attribute 'system/permanent_ip',
          display_name: 'Permanent IP Address',
          description: 'Whether the system has a permenent IP address (http://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution).',
          required: 'optional',
          type: 'boolean',
          recipes: ['system::hostname', 'system::default']
```

**Comment by alainchiasson** [comment]
The second issue - and it is more my issue - I don't think I can pass a boolean via right scale inputs - only a string. 

I noticed ['system']['permanent_ip'] is a true or false and via rightscale I can only pass it in as "true" or "false".

Or have you worked around this ?

**Comment by flaccid** [comment]
@alainchiasson there is two reasons why this is not compatible in RightScale - first is that the RightLink agent uses a version of Chef before boolean (https://tickets.opscode.com/browse/CHEF-4075) was supported and the second is that boolean isn't supported for RS inputs either.

Having used to work at RightScale and still use it daily, I should of known better. Let me fix this up so its a string.

**Comment by flaccid** [comment]
This should be fixed now in https://github.com/xhost-cookbooks/system/releases/tag/v0.4.1. Please re-open if any issues.

**Comment by alainchiasson** [comment]
Again, many Thanks. I will try it out!!
