### ISSUE TITLE
does not work with docker

### ISSUE THREAD

**Issue by epcim** [xhost-cookbooks/system#13]
I have just cloned this repo, changed driver name to `docker` in `.kitchen.yml` (... tested only ubuntu suites).

kitchen converge fails on:
```           ================================================================================
             Error executing action `run` on resource 'execute[run hostname]'
             ================================================================================
             
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of hostname test.kitchen ----
             STDOUT: 
             STDERR: hostname: you must be root to change the host name
             ---- End output of hostname test.kitchen ----
             Ran hostname test.kitchen returned 1
```
Note use_sudo/sudo: true didn't helped.
I believe previous versions did worked on docker. However I have not yet found what changed...

**Comment by flaccid** [comment]
@epcim checkout things found on google such as:
 - https://github.com/docker/docker/issues/243
 - https://github.com/docker/docker/issues/8902

So I guess that means we shouldn't run the hostname command if in a container, so the question is how to check if within a container.

**Comment by flaccid** [comment]
c/o coderanger. https://github.com/poise/poise-service/blob/master/lib/poise_service/service_providers/upstart.rb#L34

**Comment by flaccid** [comment]
https://github.com/chef/ohai/issues/531 was raised. I think we'll need that fixed to ensure support coverage and determine if the same logical check will be used as proposed above.

**Comment by epcim** [comment]
Well we may check node.virtualization['system'] for docker/lxc and avoid a change, however since docker 1.2.0 IMHO it's possible to modify even /etc/hosts, /etc/resolv.conf etc.. (https://github.com/docker/docker/pull/5129). 

My use-case is functional cookbook testing in docker. I do setup hostname of deployed servers to /etc/hosts (just for convenience). With vagrant/vbox/aws all will work, but the same cookbook used under docker will fail.

I was actually doing the hostname change in the past on docker (https://github.com/opscode-cookbooks/chef-client/issues/248) however this time there is new issue with the root rights, which I quite don't understand why?

**Comment by flaccid** [comment]
It looks like this is more something you are trying to do with Docker. This cookbook was never designed nor supports Docker. Setting hostname in a Docker container seems like a flawed use case.

With that being said we can look at the right graceful degradation once there is an accurate ohai query.

**Comment by flaccid** [comment]
Awaiting pull request merge (https://github.com/chef/ohai/pull/569) and then release.

**Comment by flaccid** [comment]
I was hoping to do much better but the limitations are all upstream.
Added a `.kitchen.docker.yml` (https://github.com/xhost-cookbooks/system/commit/7add96204623d7fef8f33f32f38e341da40536fc). You still can't use hostname set within container, it must be done with `docker -h`. Its not practical to support a test suite with increased privilege to the test containers.
