### ISSUE TITLE
[suggestion] variable inside regex

### ISSUE THREAD

**Issue by chrisduong** [xhost-cookbooks/system#14]
Hi,

In the `hostname` provider snippet, line 158

```ruby
not_if { ::File.readlines('/etc/sysconfig/network').grep("HOSTNAME=#{fqdn}").any? }
```
The variable does not expand correctly making it is always false.

I changed to

```ruby
not_if { ::File.readlines('/etc/sysconfig/network').grep(/HOSTNAME=#{fqdn}/).any? }
```

This fix would make Redhat family won't restart the network everytime the Chef run

**Comment by flaccid** [comment]
Thanks for this @chrisduong. Will be out in next release.
