### ISSUE TITLE
localhost race condition

### ISSUE THREAD

**Issue by szymonpk** [xhost-cookbooks/system#17]
* hostsfile_entry[127.0.1.1] action remove (up to date)
      * hostsfile_entry[127.0.0.1] action create
      Recipe: <Dynamically Defined Resource>
        * file[/etc/hosts] action create
          - update content in file /etc/hosts from 19f69f to 5f2331
          --- /etc/hosts	2015-05-20 12:10:32.340169566 +0000
          +++ /etc/.hosts20150520-20636-1wql7uh	2015-05-20 12:11:48.040170459 +0000
          @@ -14,5 +14,4 @@
           ff02::2	ip6-allrouters
           fe00::	ip6-localnet
           ff00::	ip6-mcastprefix
          -::1	localhost
        - Create hostsfile_entry[127.0.0.1]
      * hostsfile_entry[46.101.21.109] action create (up to date)
      * hostsfile_entry[255.255.255.255] action create (skipped due to only_if)
      * hostsfile_entry[::1] action create
        * file[/etc/hosts] action create
          - update content in file /etc/hosts from 5f2331 to 19f69f
          --- /etc/hosts	2015-05-20 12:11:48.040170459 +0000
          +++ /etc/.hosts20150520-20636-w96ge0	2015-05-20 12:11:48.056170459 +0000
          @@ -14,4 +14,5 @@
           ff02::2	ip6-allrouters
           fe00::	ip6-localnet
           ff00::	ip6-mcastprefix
          +::1	localhost
        - Create hostsfile_entry[::1]

It happens every chef run, I think `unique true` should be dropped from [here](https://github.com/xhost-cookbooks/system/blob/master/providers/hostname.rb#L72-L75), it's in conflict with [::1](https://github.com/xhost-cookbooks/system/blob/master/providers/hostname.rb#L106-L108) localhost definition. But it should be tested.

**Comment by flaccid** [comment]
Which platforms and versions?

**Comment by szymonpk** [comment]
Sorry I should write this in my initial report.

    # lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.1 LTS
    Release:	14.04
Codename:	trusty

**Comment by flaccid** [comment]
Released in 0.6.4.
