### ISSUE TITLE
Reflect which recipes are enabled by default in the README.md

### ISSUE THREAD

**Issue by nkadel-skyhook** [xhost-cookbooks/system#19]
Please indicate which recipes are  included by 'recipe[system::default]' in the README.md It will help avoid any confusion as to whether 'recipe[system::updates]' or any other need to be activated manually or are included by default.

**Comment by flaccid** [comment]
It does, https://github.com/xhost-cookbooks/system/blob/master/README.md#systemdefault. The other option is including the upgrade recipe too but I thought people would prefer to decide on that themselves.

**Comment by nkadel-skyhook** [comment]
Thanks, I'll send in a suggested patch to make it more apparent. I'd definitely not include the 'upgrade' recipe. I sat down at one point and started doing an upgrade cookbook, and got bogged down very quickly in organizing yum options, such as "--downgrade", allowing specific version control, and overriding dependencies, doing forced removals for the 'mysql-libs' dependency nightmare with different MySQL versions, the tendency of the last installed Java to blow away the java cookbook settings, etc.

**Comment by flaccid** [comment]
It's pretty apparent now and doesn't include the upgrade recipe but I'm always open to improving anything relating to usability. Your issue there just sounds like a symptom of choosing an rpm/yum based distro 😄

**Comment by flaccid** [comment]
I have improved this in the readme now, https://github.com/xhost-cookbooks/system#systemdefault.
