### ISSUE TITLE
Timezone send Error on AWS Linux

### ISSUE THREAD

**Issue by jmcollin78** [xhost-cookbooks/system#29]
I tryu to change the timezone on a AWS Linux box and I've got this error:
<pre>
[2015-10-08T20:59:15+00:00] ERROR: Could not read /opt/aws/opsworks/current/merged-cookbooks/system into a Chef object: Option default must be a kind of [String, Array, Hash]!  You passed true.
[2015-10-08T20:59:15+00:00] ERROR: #<NoMethodError: undefined method `to_hash' for nil:NilClass>
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:85:in `block in get'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:339:in `with_entry'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:82:in `get'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_base.rb:42:in `get_data'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:77:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:37:in `post'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_base.rb:29:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_router.rb:23:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/server.rb:335:in `block in make_app'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:412:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:412:in `handle_request'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:306:in `process_client'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:215:in `block in run'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `block in spawn_thread'
[2015-10-08T20:59:15+00:00] INFO: HTTP Request Returned 500 Internal Server Error:

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.

Server Response:
----------------
Exception raised!  #<NoMethodError: undefined method `to_hash' for nil:NilClass>
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:85:in `block in get'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:339:in `with_entry'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/chef_fs/chef_fs_data_store.rb:82:in `get'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_base.rb:42:in `get_data'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:77:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:37:in `post'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_base.rb:29:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/rest_router.rb:23:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/chef-zero-1.7.3/lib/chef_zero/server.rb:335:in `block in make_app'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:412:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:412:in `handle_request'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:306:in `process_client'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/server.rb:215:in `block in run'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `call'
/opt/aws/opsworks/releases/20150911163841_3427-20150911163841/vendor/bundle/ruby/2.0.0/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `block in spawn_thread'

[2015-10-08T20:59:15+00:00] ERROR: Running exception handlers
[2015-10-08T20:59:15+00:00] ERROR: Exception handlers complete
[2015-10-08T20:59:15+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2015-10-08T20:59:15+00:00] ERROR: 500 "Internal Server Error"
</pre>

I can't ge rid off this error.

Please help.

I try with the master branch without success.

My recipe is:
<pre>
Chef::Log.info("cld-apps : Setting Timezone to #{node[:system][:timezone]}")
include_recipe 'system::timezone'
</pre>
and attributes:
<pre>
default[:system][:timezone] = 'Europe/Paris'
</pre>
My Berkshelf:
<pre>
source "https://supermarket.chef.io"
cookbook 'system', '~> 0.9.1'
</pre>
My metadata.rb:
<pre>
name        "cld-envconfig"
description 'Cookbook for configuration environment of a Lunix AWS'
maintainer  "clouderial"
license     "Apache 2.0"
version     "1.0.0"

depends 'mongodb'
depends 'cld-appconfig'
depends 'system'
</pre>

**Comment by flaccid** [comment]
Looks like OpsWorks has an old version of Chef. It needs to be at least version 11.12. See https://tickets.opscode.com/browse/CHEF-4075. You could try to override any attributes using a boolean and pass string instead. Ask AWS to upgrade or better yet use stock Chef 😆

**Comment by jmcollin78** [comment]
Yep. OpsWorks is 11.10 or 12.2 for Windows users.More info here: http://docs.aws.amazon.com/fr_fr/opsworks/latest/userguide/workingcookbook-chef11.html
