### ISSUE TITLE
Add support for Ubuntu 15.04 (systemd)

### ISSUE THREAD

**Issue by fletchowns** [xhost-cookbooks/system#30]
It would be awesome if this cookbook supported Ubuntu 15.04 (which uses systemd by default).

**Comment by fletchowns** [comment]
I'm in a bit of catch 22 now between this and https://github.com/chef-cookbooks/openssh/issues/68 :)

**Comment by flaccid** [comment]
All good now thanks @fletchowns. @tas50 might be able to help with the openssh cookbook.

**Comment by fletchowns** [comment]
Shweet, thanks @flaccid !
