### ISSUE TITLE
sanity check for hostsfile management, skip if IP not is empty

### ISSUE THREAD

**Issue by epcim** [xhost-cookbooks/system#35]
if private/ipaddress is empty - skip

Example:
```
10.134.203.208   * ruby_block[update hostname in /etc/rc.conf] action run (skipped due to only_if)
10.134.203.208   * hostsfile_entry[127.0.1.1_chefdb3] action remove (skipped due to only_if)
10.134.203.208   * hostsfile_entry[127.0.0.1_chefdb3] action create (skipped due to only_if)
10.134.203.208   * hostsfile_entry[_chefdb3] action create (skipped due to only_if)
```

in my case, it's caused by "specific" environment, there is defaul route on bond0:1 interface, and even if set as primary_interface and using custom ohai-plugin to update ipaddress 'chef ecosystem' is only trying to find address on bond0 (not bond0:1) etc.. this way is constructed `hostsfile_entry[_chefdb3]` with missing IP.

**Comment by flaccid** [comment]
@epcim Use case makes sense, I'm assuming at the moment this means `primary_ip` comes back empty. In that situation I added some quick logic - can you test https://github.com/xhost-cookbooks/system/commit/f87ee5db1db21803ce82065ebc53d465d834e3f0 ?
I'll close this out as fixed now but we'll re-open if its not solved.
