### ISSUE TITLE
/etc/hostname should not contains the FQDN

### ISSUE THREAD

**Issue by gionn** [xhost-cookbooks/system#37]
Hi,

I never configured `/etc/hostname` with the FQDN, but this cookbooks seems to do it by default.

In fact, if I put a 64 characters long hostname (that is a valid size for an hostname):

```
  node.set['system']['short_hostname'] = 'vou3eeng7voc6eechoh6huico6zieghah9maeth9zuqu7ohjohth3rizei7oi0oh'
  node.set['system']['domain_name'] = 'unconfigured.cloudesire.com'
  include_recipe 'system::hostname'
```

 I get:

```
             Expected process to exit with [0], but received '1'
       ---- Begin output of hostname vou3eeng7voc6eechoh6huico6zieghah9maeth9zuqu7ohjohth3rizei7oi0oh.unconfigured.cloudesire.com ----
             STDOUT: 
             STDERR: hostname: name too long
             ---- End output of hostname vou3eeng7voc6eechoh6huico6zieghah9maeth9zuqu7ohjohth3rizei7oi0oh.unconfigured.cloudesire.com ----
             Ran hostname vou3eeng7voc6eechoh6huico6zieghah9maeth9zuqu7ohjohth3rizei7oi0oh.unconfigured.cloudesire.com returned 1
```

Ubuntu 14.04

**Comment by flaccid** [comment]
```
>>> len('vou3eeng7voc6eechoh6huico6zieghah9maeth9zuqu7ohjohth3rizei7oi0oh')
64
>>> len('vou3eeng7voc6eechoh6huico6zieghah9maeth9zuqu7ohjohth3rizei7oi0oh.unconfigured.cloudesire.com')
92
```
```
$ getconf HOST_NAME_MAX
64
```
```
$ sudo hostname vou3eeng7voc6eechoh6huico6zieghah9maeth9zuqu7ohjohth3rizei7oi0oh.unconfigured.cloudesire.com
hostname: sethostname: Invalid argument
```
When you set a domain name, the canonical hostname will be set which is > 64 chars.
Either make the total 64 or reduce the length of the short hostname.
64-bit short hostname is a bit loco :)

**Comment by gionn** [comment]
Just found [this](http://stackoverflow.com/a/28918017/547195) that almost replied to my concerns, it looks like that `/etc/hostname` should not contains anymore the short hostname as it was in the past, and if I get crashes the fault is on software relying on gethostname() that returns a string long at max 64 characters.

Thanks!

**Comment by flaccid** [comment]
Looks like you could be right considering http://www.freedesktop.org/software/systemd/man/hostname.html. Might look at a fix so only the short hostname is populated in `/etc/hostname`.

**Comment by flaccid** [comment]
Ok we're good now. Thanks for this @gionn.

**Comment by gionn** [comment]
Great @flaccid !

Just for the records, I've had a catastrophic failure on GCE setting in /etc/hostname something longer than 64 characters, and on reboot cloud-init failed miserably while checking if sshd host key were in place with `gethostname: File name too long`, actually wiping sshd host keys and leaving me stuck outside :+1:

**Comment by flaccid** [comment]
lol ok at least my initial thoughts were not so ignorant maybe :)

**Comment by leshik** [comment]
Just out of curiosity, may I ask what is the purpose of 'mode 0755' for /etc/hostname? It has 0644 usually on most systems...

**Comment by leshik** [comment]
I also noticed that the hostname is set to FQDN, regardless that /etc/hostname contains only host part. In my understanding, `hostname` should yield only host part, `hostname -d` should yield the domain name and `hostname -f` should yield FQDN, at leas on Linux.

**Comment by flaccid** [comment]
@leshik looking into now; i'll start with serverspec tests.

**Comment by flaccid** [comment]
@leshik looking through http://linux.die.net/man/1/hostname it looks like the current behaviour is correct, because we set a domain name, `getbyhostname(2)` will return with the domain name. I assume if you do not set a domain then `hostname` would be the same as `hostname -s`. If you are using no domain name and there is something not right could you please raise a new issue with details?

I'm looking at the `/etc/hostname` permission now and will have some commits including new tests for the above.

**Comment by flaccid** [comment]
In a little better state now. Please raise a new issue for anything you'd like to report related, thanks!
