### ISSUE TITLE
Does this require timedatectl?

### ISSUE THREAD

**Issue by gsdevme** [xhost-cookbooks/system#38]
Looks like from the code it requires `timedatectl` to be installed, however on my base cent6.7 box that is not installed..

The symlink will be in-place for next boot but won't function until I restart, is this correct?

**Comment by flaccid** [comment]
If the `timedatectl` command is found in path, `timedatectl set-timezone #{zone_file}` is executed.
https://github.com/xhost-cookbooks/system/blob/master/providers/timezone.rb#L75-L82
As far as I know only the symlink is required (line 84) in EL 6 (http://www.cyberciti.biz/faq/centos-linux-6-7-changing-timezone-command-line/). Is this happening for you @gsdevme ?

**Comment by gsdevme** [comment]
I have an issue on cent6.7 where by its only set after I reboot the server

**Comment by flaccid** [comment]
Can you provide the output of the initial chef run and we'll look at duplicating it with test kitchen and ensure we have enough tests in serverspec?

**Comment by gsdevme** [comment]
Well does the test kitchen work on your setup? I think I have a vagrant issue with versions.

**Comment by gsdevme** [comment]
I will paste the output tomorrow, midnight here in UK work laptop is packed up

**Comment by flaccid** [comment]
I've improved the tests related to timezone and bumped the kitchen to use centos 6.7 (https://github.com/xhost-cookbooks/system/commit/755383a4c8b99480a6d11ef245839bca74861b72), tests are still passing fine. I'll close this one out for now, issue appears to be local to you.
