### ISSUE TITLE
Directions provided in Testing.md do not work

### ISSUE THREAD

**Issue by rbclark** [xhost-cookbooks/system#39]
While attempting to make some small changes to this project I noticed that when running the commands as described in TESTING.md that they did not work. Specifically after running a bundle install I ran `bundle exec strainer test` and received the error 

    $ bundle exec strainer test
    bundler: command not found: strainer
    Install missing gem executables with `bundle install`

I was able to work around this somewhat by manually installing the strainer gem.

**Comment by flaccid** [comment]
@rbclark thanks for raising this. I have fixed `TESTING.md`. Let me know if you have any issues or further questions.
