### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by razor-x** [xhost-cookbooks/system#43]
Just tried to add this cookbook to my project, but all my chefspec tests are failing now because the latest release is missing this fix: aa9b9c3714cc19ea5c051f73be1e33d013027dea.

Any chance for a new release, or at least a patch version with that fix?

**Comment by flaccid** [comment]
Some good changes in there :)
https://supermarket.chef.io/cookbooks/system/versions/0.11.0
https://github.com/xhost-cookbooks/system/releases/tag/v0.11.0

**Comment by razor-x** [comment]
@flaccid :cool: Awesome, just sat down to work on this to see you cutting the new release. Tests passing again :+1:
