### ISSUE TITLE
Passing node.name to short_hostname downcases Config::Chef[:node_name], resulting in 401 errors

### ISSUE THREAD

**Issue by rubeon** [xhost-cookbooks/system#44]
The following recipe snippet results in changing the Chef node's name to lowercase. 

If the node name in Chef contains uppercase characters, this will break further attempts to authenticate to the server, e.g. during the reporting handler.  

This generates 401 authentication errors during later authentication attempts, because the client name no longer matches the one in the Chef server.

Example:

```ruby

log 'nodename-before' do
  message Chef::Config[:node_name]
  level :warn
end

static_hosts = { '127.0.0.1' => 'localhost ',
                 '10.1.1.254' => 'ftp.internal.example.com' }

my_short_name = node.name

system_hostname my_short_name do
  short_hostname my_short_name
  domain_name 'internal.example.com'
  static_hosts static_hosts
end

log 'codename-after' do
  message Chef::Config[:node_name]
  level :warn
end
```

I'm guessing this happens in `system/providers/hostname.rb`, lines 32-33:

```ruby
  new_resource.short_hostname.downcase! if new_resource.short_hostname
  new_resource.domain_name.downcase! if new_resource.domain_name

```

**Comment by flaccid** [comment]
@rubeon are you somehow using a hostname with one or more uppercase letters on a UNIX like system which is used as the CN in the cert? Curious on the why and an example.. always lowercase for me.

**Comment by rubeon** [comment]
Hi,

the Chef node names are uppercase, since that's the style my customer uses.  The UNIX hostnames I'm not really bothered about, since the UNIX resolver is case-insensitive.  They can be downcased for aesthetics.

However: Chef matches the value of `Chef::Config[:node_name]` against the client certificate, and it *is* case-sensitive. 

The LWRP shouldn't globally change the value of passed variables with the `downcase!` call, in my opinion. If it wants to downcase the hostname, it should set a local variable to the downcased value and use that instead.

**Comment by flaccid** [comment]
That's thing the though, the downcase is all done within this cookbook anyway and is used with setting hostname only. If `Chef::Config[:node_name]` derives itself from fqdn or hostname in ohai this is always going to change if the hostname is changed. I assume you are using chef client as opposed to solo or zero?
Need someone from Chef Software to advise here.

**Comment by rubeon** [comment]
Hi, 

your recipe is changing the value of `Chef::Config[:node_name]` with the '!' on the `downcase!` call.  

You redefine it in your recipe; Chef doesn't derive it from the hostname or anything else, it gets it from `client.rb`. 

If I copy `Chef::Config[:node_name]` to a different variable and pass that instead, I don't have this issue.

This is how I'm working around the issue:

```ruby
# Normalise the node / environment names for dns-friendliness
short_hostname = "#{node.name}".sub('_', '-')
domain_name = "#{node.chef_environment}.int.example.com".sub('_', '-')
system_hostname short_hostname do
  short_hostname short_hostname
  domain_name domain_name
  static_hosts static_hosts
end
```

**Comment by flaccid** [comment]
I'm just trying to understand how that is explicitly being done to `Chef::Config[:node_name]` itself if the code is https://github.com/xhost-cookbooks/system/blob/master/providers/hostname.rb#L32-L33 on the short hostname and domain name provided with the new resource.
Something I must not understand with ruby/chef if that is the case. Please educate me :)
Also keep in mind your example above the `system_hostname` resource is done in compile time not execution of the resource below it.

**Comment by rubeon** [comment]
I think we've wandered a bit, so to clarify: as in the title, this happens when passing `node.name` to the `system_hostname` resource.  

Whatever variable it receives, `system_hostname` changes the value of it in-place.  The affects the remainder of the chef-run.  In this case, passing a global like node.name will affect other recipes using it after `system_hostname`.

This is caused by `system_hostname` taking the argument `new_resource.short_hostname`, which is a reference to `node.name` in this use case, and changing its value with an in-place downcase: `new_resource.short_hostname.downcase!`. It's setting the value of node.name (a global) to node.name.downcase. Since `node.name` is a pointer to `Chef::Config[:node_name]`, it gets changed.

**Comment by flaccid** [comment]
Looking at this:

```
# Normalise the node / environment names for dns-friendliness
short_hostname = "#{node.name}".sub('_', '-')
domain_name = "#{node.chef_environment}.int.example.com".sub('_', '-')
```
That is also specific to I guess chef client. The cookbook is not intended to be specific to it - you can specify your own strings for the hostname and domain names, its up to you what you'd like to derive it from.

I can provide some extra sanitization such as underscore to hyphen but its up to the user to the values they would like. The two you provided afaik won't exist in chef-solo/standalone ohai.

You can certainly override the defaults that are inherited from the default attributes file also.

**Comment by flaccid** [comment]
I expect that changing the hostname will change `node.name`, `Chef::Config[:node_name]`. Let's look up how that is derived first.

**Comment by flaccid** [comment]
Without looking up the code, i'm guessing its the same has `node['fqdn']` or `node['hostname']` which of course will change to what the hostname gets set to.

**Comment by rubeon** [comment]
Well, if I pass a different variable to system_hostname with the same value as `node.name`, `node.name` isn't affected. That's a pretty good indicator that it isn't being derived from the hostname.

**Comment by flaccid** [comment]
This might be pretty simple, referring to https://docs.chef.io/config_rb_client.html
`node_name`
    *The name of the node. Determines which configuration should be applied and sets the client_name, which is the name used when authenticating to a Chef server. The default value is the FQDN of the chef-client, as detected by Ohai. In general, Chef recommends that you leave this setting blank and let Ohai assign the FQDN of the node as the node_name during each chef-client run.*
```

**Comment by flaccid** [comment]
@rubeon since capitals in hostnames are valid and supported in most unix-like systems I have removed the downcase and also chose to do no other token processing of the attributes. We'll raise if an invalid hostname is detected - I think its better that users learn to provide valid hostnames.

I think this should solve it for you, just keeping in mind that you may need to still do your own string changes for hostname and domain name first, e.g.

```
system_hostname short_hostname do
  short_hostname "#{node.name}".sub('_', '-')
  domain_name "#{node.chef_environment}.int.example.com".sub('_', '-')
end
```

I have not used this cookbook with chef client, so happy to accept pull requests to improve the readme on how it might best be used with nodes.
