### ISSUE TITLE
Setting hostname leads to uninitialized constant…

### ISSUE THREAD

**Issue by alappe** [xhost-cookbooks/system#45]
With `0.11.0` I get the following error:

```
================================================================================
Error executing action `set` on resource 'system_hostname[dodo]'
================================================================================

NameError
---------
uninitialized constant #<Class:0x0000000501e938>::Chef::Runner

Cookbook Trace:
---------------
/home/acme/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/home/acme/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/home/acme/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/home/acme/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/home/acme/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Resource Declaration:
---------------------
# In /home/acme/.chef/local-mode-cache/cache/cookbooks/system/recipes/hostname.rb

 20: system_hostname node['system']['short_hostname'] do
 21:   short_hostname    node['system']['short_hostname']
 22:   domain_name       node['system']['domain_name']
 23:   static_hosts      node['system']['static_hosts']
 24:   netbios_name      node['system']['netbios_name']
 25:   workgroup         node['system']['workgroup']
 26:   manage_hostsfile  node['system']['manage_hostsfile']
 27:   not_if            { node['virtualization'] && node['virtualization']['system'] && node['virtualization']['system'] == 'docker' }
 28: 
 29:   # https://github.com/chef/ohai/pull/569 not yet in most used chef versions
 30:   not_if            'ls /.dockerinit'
 31: end

Compiled Resource:
------------------
# Declared in /home/acme/.chef/local-mode-cache/cache/cookbooks/system/recipes/hostname.rb:20:in `from_file'

system_hostname("dodo") do
  action :set
  updated true
  updated_by_last_action true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :system_hostname
  cookbook_name "system"
  recipe_name "hostname"
  short_hostname "dodo"
  domain_name "example.com"
  netbios_name "DODO"
  workgroup "WORKGROUP"
  manage_hostsfile true
  hostname "dodo"
  not_if { #code block }
  not_if "ls /.dockerinit"
end
```

chef `12.5.1`

**Comment by flaccid** [comment]
@alappe curious on how I might be able to replicate this. How did you install chef and which os/distro is this on? Please also provide the an example `node.json` (node attributes).
Also, does it occur on any earlier versions of the cookbook?

**Comment by alappe** [comment]
I added a broken down setup to replicate the issue here:

https://github.com/alappe/hostname-testcase

I run it with `vagrant up --provider virtualbox`.

It needs vagrant, virtualbox, the vagrant-berkshelf plugin. Both `0.11.0` and `0.11.1` break with this setup, `0.10.1` works. It is on ubuntu 14.04. The node file chef creates is boring, supposedly because it breaks on the run…

```
{
  "name": "vagrant-ee435652"
}
```

**Comment by flaccid** [comment]
Thanks for doing that! Will work on diagnosing this tonight or if not this week for sure.

**Comment by flaccid** [comment]
`compat_resoruce` cookbook is a dep of the `apt` cookbook. Perhaps not a specific bug yet https://github.com/chef-cookbooks/compat_resource/issues?utf8=%E2%9C%93&q=uninitialized%20constant.

**Comment by flaccid** [comment]
With Chef `12.14.77` this issue does not occur with `compat_resource 12.4.6`. In that case its an upstream bug in that cookbook where it has an issue with one or more versions but in particular `12.5.1`. Easy fix is to upgrade Chef or if really needed, raise a bug with `compat_resource` or `apt` cookbook(s).

Unfortunately, nothing I can do from here but I do note that the version of `apt` (2.8.2 vs. 4.0.2) used at the time of `system 0.10.1` didn't seem to depend on/use `compat_resource` (https://github.com/xhost-cookbooks/system/blob/v0.10.1/Berksfile.lock#L7).

**Comment by alappe** [comment]
Thanks!
