### ISSUE TITLE
apt in core

### ISSUE THREAD

**Issue by Spreadcat** [xhost-cookbooks/system#51]
with the apt cookbook now in the core module, the dependency cookbook 'apt' might be obsolete, right?

[2016-11-14T14:01:27+00:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2016-11-14T14:01:27+00:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt

**Comment by flaccid** [comment]
Which version Chef are you using there, also any links on this change and in which Chef version? Are you saying the apt LWRPs are now in Chef itself?

**Comment by Spreadcat** [comment]
I'll have a look for you tomorrow which exact version I am running. My guess is at around 12.16 or something.
As far as I understand [the documentation](https://docs.chef.io/resource_apt_repository.html), are all those commands now in the core as well. The change was somewhere around 12.8 IIRC. But I will checkout the details tomorrow (~11h from now) when I have access again.

**Comment by flaccid** [comment]
The issue is likely that I still want to support Chef 11.

**Comment by Spreadcat** [comment]
Ofc. Any way of excluding the double declaration when the client version is higher than a certain version? I'll guess there will be more requests in the long term coming up in the future.
Otherwise it doesn't seem to be a big issue. The code is still running through (just with warnings) and as far as I can see the changes are deployed as well.
I just try to avoid changing the community cbooks directly in order to not break any future releases, so just doing it internally for my wouldn't be a solution. I guess I'll just work around in wrapper or something then. ;)

**Comment by flaccid** [comment]
If so, hopefully not messy. Can check tonight after work or at least we'll sort it out this week.

**Comment by Spreadcat** [comment]
The client version is 12.16.

**Comment by flaccid** [comment]
@Spreadcat I don't think this is going to be possible. Its the `depends` in `metadata.rb` that triggers this warning. Because of http://stackoverflow.com/questions/25905481/dynamic-metadata-according-platform and we want to support Chef 11 and earlier versions of Chef 12, I currently do not see a way to address this. Let me know if you have any ideas.

**Comment by flaccid** [comment]
No response, closing.
