### ISSUE TITLE
cron dependency is too loose

### ISSUE THREAD

**Issue by veetow** [xhost-cookbooks/system#52]
The cookbook depends on 'cron' with no version requirements:
https://github.com/xhost-cookbooks/system/blob/v0.11.2/metadata.rb#L27

But it uses attributes from the cron cookbook that did not exist until version `1.7.0`:
https://github.com/chef-cookbooks/cron/tree/v1.7.0/attributes

I propose adding a `'>= 1.7.0'` to this dep.

**Comment by flaccid** [comment]
Thanks!
