### ISSUE TITLE
Old cron dependency

### ISSUE THREAD

**Issue by gfrntz** [xhost-cookbooks/system#55]
Hello,
Why you pin cron cookbook version to '~>1.7'? May be fix it to '> 1.7'?

Best regards

**Comment by flaccid** [comment]
From memory this is something historic around bugs and support issues with the distros which are probably solved now. I can remove the pin, but we'll need to do some pretty thorough semi/manual testing?

**Comment by flaccid** [comment]
@gfrntz ok thats relaxed in master now. Be great if you could help with some general manual testing across the board!

**Comment by gfrntz** [comment]
I'll try to test it. Bump version, please. Thanks.

**Comment by flaccid** [comment]
No new version until we test.

**Comment by gfrntz** [comment]
Ok, thanks.

**Comment by olbrich** [comment]
any progress on testing this?

**Comment by gfrntz** [comment]
So, i can't found any problems with this merge in my infrastructure.

**Comment by flaccid** [comment]
To complete, this is more about updating the dev files and making this pass. Its a bit of an uplift I didn't find time to finish. Let me resurrect it now.

**Comment by flaccid** [comment]
Everything we need for this including the dev/style fixes is in master now. I'm going to see if there is anything else I should include before cutting a release. All the major distros are passing fine.

**Comment by flaccid** [comment]
New release will be out shortly.
