### ISSUE TITLE
0.11.3 Release Contains Damaged host_find.rb

### ISSUE THREAD

**Issue by bbnathan** [xhost-cookbooks/system#56]
`# cat  /var/chef/cache/cookbooks/system/libraries/PaxHeader/host_info.rb
18 gid=1948946360
18 uid=1331798847
20 ctime=1499924390
20 atime=1499924390
23 SCHILY.dev=16777220
23 SCHILY.ino=53865846
18 SCHILY.nlink=1

This is possibly related to: 

https://tickets.opscode.com/browse/CHEF-4107
https://github.com/berkshelf/berkshelf/issues/1132
`

**Comment by bbnathan** [comment]
yes

**Comment by flaccid** [comment]
Ignore the incorrect ref in commit (it was for issue #55). Another release is about to come out - please open a new issue if the problem still exists. It should be fixed now upstream.
