### ISSUE TITLE
Wrong hostname parsing

### ISSUE THREAD

**Issue by gfrntz** [xhost-cookbooks/system#57]
Hello,
I trying to use system::hostname recipe and i found a bug in parsing. 

When I use four level domain like ```some.kind.of.domain``` recipe sets ```some.of.domain```.

**Comment by flaccid** [comment]
@gfrntz can you please show me the json node attributes you are using specifically?

**Comment by gfrntz** [comment]
You know, I cant reproduce this bug. When I started using `system::hostname` i didn't set nothing and cookbook overrides 4 level domains to 3 level domains. Now cookbook sets .localdomain entry to my hosts file. I should set 'domain_name' attr and all will be ok. So, i think you can close my issue. And sorry to bother you.

**Comment by flaccid** [comment]
Np!
