### ISSUE TITLE
Resource: system::hostname is always returning "action set" if the /.dockerinit file is not created

### ISSUE THREAD

**Issue by rbprado** [xhost-cookbooks/system#61]
Hi, I am experiencing a behavior using this cookbook that looks pretty weird.

I am using this cookbook to set some attributes on some physical machines (not VMs or containers):
- `timezone`
- `domain_name`
- `static_hosts`

On each run of the chef-client it says to be setting the `Resource system_hostname[dmos-buildator-slave1] received action "set"`

The log of chef-client -l debug says:
```
Recipe: system::hostname
  * system_hostname[dmos-buildator-slave1] action set[2017-12-11T08:36:36-02:00] INFO: Processing system_hostname[dmos-buildator-slave1] action set (system::hostname line 20)
ls: cannot access /.dockerinit: No such file or directory
```
![print-chef](https://user-images.githubusercontent.com/7606439/33829069-b4dfdc8a-de55-11e7-8327-af52973ed595.png)

If I just touch the `/.dockerinit` file on this machine the chef-client says that it's OK and no change is required:
```
Recipe: system::hostname
  * system_hostname[dmtdd-slave9] action set (skipped due to not_if)
```

This machine do not even has docker installed.

Do you know why is that happening?

Versions:
CentOS Linux release 7.4.1708 (Core) on the physical slave in which the chef-client is running.
Chef client: 13.6.4

**Comment by flaccid** [comment]
Would be to be expected due to https://github.com/xhost-cookbooks/system/blob/45724fece4cfdf0f028c3878562fe8226ad79958/recipes/hostname.rb#L29-L30 - I assume you don't see an error with info level?

**Comment by rbprado** [comment]
Yes, there is no error, just info warning, but the thing is the playbook is not being able to get the data if there is no `/.dockerinit` file, so, it will be always saying there are resources being "set" unnecessarily.

The data has not changed, but for each new run of chef-client without the `/.dockerinit` will says that these data has been updated cause they were blank (as the print posted before).

**Comment by flaccid** [comment]
Playbook?

**Comment by flaccid** [comment]
@rbprado added a 'fix', thats the best I can do. The method used here is a good practice. Multiple runs still result in the hostname resource not being updated. I still believe the problem is on your end and whatever you are doing, there is no change in behaviour before and after the fix.

With my kitchen test:
```
       Recipe: system::hostname
         * system_hostname[test] action set
           * execute[run hostname] action run (skipped due to not_if)
           * ruby_block[update hostname in /etc/rc.conf] action run (skipped due to only_if)
           * hostsfile_entry[127.0.1.1_test] action remove (up to date)
           * hostsfile_entry[127.0.0.1_test] action create (up to date)
           * hostsfile_entry[172.16.172.16_test] action create (up to date)
           * hostsfile_entry[255.255.255.255_test] action create (skipped due to only_if)
           * hostsfile_entry[::1_test] action create (up to date)
           * hostsfile_entry[fe00::0_test] action create (up to date)
           * hostsfile_entry[ff00::0_test] action create (up to date)
           * hostsfile_entry[ff02::1_test] action create (up to date)
           * hostsfile_entry[ff02::2_test] action create (up to date)
           * hostsfile_entry[95.211.29.66_test] action create (up to date)
           * hostsfile_entry[184.106.28.82_test] action create (up to date)
           * service[hostname.sh] action nothing (skipped due to action :nothing)
           * service[network] action nothing (skipped due to action :nothing)
           * execute[run hostname] action nothing (skipped due to action :nothing)
           * ruby_block[update network sysconfig] action run (skipped due to only_if)
           * ruby_block[show hostnamectl] action nothing (skipped due to action :nothing)
           * execute[run hostnamectl] action run (skipped due to not_if)
           * execute[run domainname] action nothing (skipped due to action :nothing)
           * file[/etc/cloud/cloud.cfg.d/01_preserve_hostname.cfg] action create (skipped due to only_if)
           * execute[update hostname via nmcli] action run (skipped due to only_if)
           * service[systemd-hostnamed] action nothing (skipped due to action :nothing)
           * ruby_block[show host info] action nothing (skipped due to action :nothing)
           * file[/etc/hostname] action create (up to date)
           * execute[ensure hostname sync'd] action run (skipped due to not_if)
           * execute[set rightscale server hostname tag] action run (skipped due to only_if)
            (up to date)
```
Multiple runs will have this same result after the hostname is set. Chef will always log, 'action set', what you should be looking for is '(up to date)' which indicates the resource has not changed.
