### ISSUE TITLE
timezone data does not function for ubuntu.

### ISSUE THREAD

**Issue by alainchiasson** [xhost-cookbooks/system#8]
When using the timezone on a Ubuntu machine, the /etc/timzone file is not set.

**Comment by alainchiasson** [comment]
Found the following : 

```
  if %w(debian ubuntu').member? node['platform']
    package 'tzdata'
```

The single quote after the ubuntu causes the platform to not match.

**Comment by flaccid** [comment]
Thanks for the fix @alainchiasson !

**Comment by alainchiasson** [comment]
Happy to help! Thanks for the cookbook!

Alain Chiasson
